### ISSUE TITLE
Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0)

### ISSUE THREAD

**Issue by lcj820** [shicai/MobileNet-Caffe#42]
Hi!
when i run the net,i meet this issue:
Check failed: status == CUDNN_STATUS_SUCCESS (4 vs. 0) CUDNN_STATUS_INTERNAL_ERROR
***./experimrnts/scripts/faster_rcnn_end2end.sh:line 57 :14240 Aborted

can you help me?thanks!

**Comment by shicai** [comment]
please use caffe engine instead of cudnn engine.

**Comment by lcj820** [comment]
ok，thanks

**Comment by lcj820** [comment]
@shicai  hi,
 File “/home/work-station/zx/py-faster-rcnn/tools/../lib/rpn/anchor_target_layer.py”, line 137, in forward

gt_argmax_overlaps = overlaps.argmax(axis=0)

ValueError: attempt to get argmax of an empty sequence


when i try the mobilenet ,this question will happen, and how to solve it?
emmmm,but when i try the ZFNET, it's  OK.  why?
others say: Because the ratio of images width and heights is too small or large ,i think it maybe br wrong for me ,because the database is same for zfnet or mobilenet!
thanks

**Comment by shicai** [comment]
check the total feature strides of the two networks, make sure they are of the same size.

**Comment by lcj820** [comment]
@shicai First of all thank you very much for your advice ！
for some question i feel confused. for the mobilenet ,the num_out is 1000 , but my num_out is 2 .if i just change the num__out, this question will happen:
cannot copy param from layer 'fc7' :shape mismatch .source parm is 1000 1024 1 1 (1024000);target parm shape is 2 1024 1 1(2048).to learn this layer's parameters from scratch rather than copying from a saved net ,rename the layer.         ----First question 
in order to solve this question ,i add the layer 'fc8' to set the num_out 2,rather than modify the layer 'fc7'.
so when i run the net ,another question happen. 
ValueError: attempt to get argmax of an empty sequence.    --- i learn from you yesterday how to solve it！
do you think Is there any connection between the two question？ and for the first question whether it's right to add layer？
thanks

**Comment by shicai** [comment]
Since you are finetuning ImageNet models, you should change the name and the num_output of the last layer (eg: fc7 -> fc7x, 1000->2) for classification tasks. but for detection tasks, you'd better remove poo6 and fc7 layers, and add your own layers.

**Comment by lcj820** [comment]
thanks

**Comment by zihao-lu** [comment]
Do you mean than i should modify the DEFAULT to CAFFE in "optional Engine engine = 15 [default = DEFAULT]"  of caffe/src/caffe/proto/caffe.proto?

**Comment by zihao-lu** [comment]
If yes, i try to do this but there is still  the similar problem, ennnnnn, what should i do? thanks

**Comment by sarathsrk** [comment]
This fixed issue for me....
`sudo chown -R $USER: $HOME`

**Comment by yuxwind** [comment]
Actually, I was out of GPU memory. After killing some application, the error is fixed.
